### PR TITLE
Update HVProgrammer.cpp

### PR DESCRIPTION
**Pull request by bWildered1**
When the lock bits are set it is not possible to write fuses. A chip erase is the only way to clear locks bits.
Also added is user options to select fuse write to defaults, chip erase or just fuse read via Serial Monitor character entry.

### CODE REVIEW

**Comment by ArminJo** [comment]
Hello bWildered1
thank you very much for your valuable additions!
I added them manually and set the dafault (button) behavior to writing fuses.
Can you test the chip erase and give me feedback?
Thanks in advance
Armin

**Comment by bWildered1** [comment]
Hi Armin

I have tested the new Arduino HV Serial Fuse programmer with an ATtiny85 device.
With a non-locked ATtiny85 this can write fuses to their default values using both keyboard entry and the Arduino connected switch. With a locked device it can erase the device memories when this option is selected via the keyboard ('e'). It  can report the existing fuse values via the keyboard read entry command ('r') for both locked and non-locked devices. 

I hope this is what you need.

Take care

Mike

**Comment by ArminJo** [comment]
Hi Mike,
thank you very much for your testing!!!
So I hope our work will help others struggling with locked ATtinies.
Alles Gute
Armin

**Comment by bWildered1** [comment]
You are very welcome Armin.
It is nice to be able to contribute. Even a little.
A suggestion...
If the program operated in a loop, then the user could enter a sequence of commands. 
For example, a user could read the device fuses. If OK, the user could quit at this stage.
But the user could instead proceed to writing the fuse defaults.
If this failed, then user could then erase. 
And follow up with a fuse program.
All within a single session.
Eg. 'r', 'w', 'e', 'w', 'q'
where 'w' and 'q' are used to write to the fuses and quit respectively. ('f' might be better for the fuses).

But anyway, thank you for creating this, and making it available to the community.

Take care

Mike

**Comment by ArminJo** [comment]
Hi Mike,
such a great idea, I must implement! I omitted only the q since quitting on an Arduino seems somehow a bit sensless.
Maybe yo try the new source?
Grüße
Armin

**Comment by bWildered1** [comment]
Hi Arnin

Sorry about the delay in getting back to you.
Busy.

I have just done a quick check on the latest code, and it continually spits
out the instructions.

I modified the opening part of loop to address this.
void loop() {

    Serial.println();
    Serial.println("Enter 'f' to only read fuses...");
    Serial.println("Enter 'e' to erase flash and lock bits...");
    Serial.println("Enter 'w' or any other character or press button at pin
6 to to write fuses to default...");
    Serial.println();

    /*
     * Wait until button pressed or serial available
     */
    char tReceivedChar = 0; // Default value taken, if button pressed

    while (!Serial.available() || !digitalRead(START_BUTTON_PIN));

    //if (!digitalRead(START_BUTTON_PIN) || Serial.available() > 0) {
        // read command
        //if (Serial.available() > 0) {
            tReceivedChar = Serial.read();
        //}


This part works, but the program does not read the device signature
properly.

There is no obvious problem.

I might get a chance to investigate further later on.


Take care

Mike

**Comment by bWildered1** [comment]
Hi Armin.

I have done some further tests and checks.

For some reason the code versioned 3.1 doesn't read from the target
successfully.

Oddly enough, reverting to the older code with the recent changes does work.

I have made some other changes as well, some just to format the printed
output so that important information is more visible, some to add some
extra printed output,  and one more significant change.
I have added a function to read and display the lock bit values, and made
calls to this function from within loop.

This version can
1) read and display fuse and lock bit values by keyboard entry
2) change fuse values in a non-locked device by keyboard entry and button
press
3) erase memories and reset lock bits by keyboard entry

I have given this code a provisional version of V3.0A

I hope to be able to upload this evening.

Take care

Mike

**Comment by ArminJo** [comment]
Hi Mike,
The loop was a stupid error of me. Should not happen!. I was too lazy to test this version. Now it is corrected.
On my board the signature reading still works, at least for an attiny85.

Looking forward to your additions.
I opend the pull request again, so you can rebase and modify.
Armin

**Comment by bWildered1** [comment]
Hi Armin

I wouldn't worry about making 'stupid errors'; I do that all the time, most
recently today.

I have put an updated version of your earlier version 3.0 code onto your
GitHub page.

But - looking at the GitHub diff - I am not convinced it would merge the
files correctly.
It's probably just the way I'm looking at it (kinda tired at the moment),
but I'll attach a copy of the code to this email.


Take care

Mike

**Comment by bWildered1** [comment]
Oh, I forgot to mention, I use the original (Arduino) pin assignments...

These will need to be 'commented out' in the code I just sent, and the
others 'commented in'.


Take care


Mike

**Comment by ArminJo** [comment]
Hi,
In the email, there is no attachement
can you send it directly  to armin.arduino@gmail.com ?

Thanks
Armin

**Comment by ArminJo** [comment]
Version 3.2
OK I hope you find it useful ;-)

**Comment by bWildered1** [comment]
Cool!

Wow, that's a lot of changes.

I'll try to set aside some time this week for some 'black box' testing.


Take care, Armin.
And thanks.


Mike

**Comment by bWildered1** [comment]
Hi Armin.

I've just done some 'black box' testing on the latest (v3.2) code.

The program
    reads and reports device signature, reads and reports device fuse
values and reads and reports lock bit values and status upon keyboard 'r'
entry
    IF LOCK BITS NOT PROGRAMMED, writes fuses to default values upon
        'w' keyboard entry
        other non 'e', non 'r' keyboard entry
        switch press
    IF LOCK BITS SET cannot write fuses, as expected

    erases flash and lock bits upon keyboard 'e' entry
        after this erase process, fuses can be written by appropriate
keyboard entry or switch press

A small matter...
Program hangs after switch used to write fuses. It does not respond to any
further input from either keyboard or switch.
Last line displayed in Serial Monitor is
'Reading fuse values complete.'


A general comment
The displays are much neater, and this makes the application much easier to
use

Good job.

Take care

Mike

**Comment by ArminJo** [comment]
Hello Mike,
Thank you for testing,
The program is supposed to "hang" and blink with the builtin LED if programming was started by button, -> the "unattended" mode.
But newertheless, I changed the check for button release.
I also added a chip erase before writing fuses, if fuses are locked, it might be useful for the "unattended" mode, which should reset fuses
Please test, if the program stll "hangs"

Besten Dank
Armin

**Comment by bWildered1** [comment]
Hi Armin

I've just done a quick test on the latest code.
This does not read the device, reporting
______________________________________
Reading signature from connected ATtiny...
Signature is: 0
Reading signature complete..

No valid ATtiny signature detected!
Try again.
______________________________________

I reverted to the previous code, which works as reported earlier.

If the program is supposed to hang after a switch initiated fuse write,
then maybe that (older) code is fine?

Take care

Mike

**Comment by ArminJo** [comment]
Strange, I just tested the latest version again, and it worked like a charm.

**Comment by bWildered1** [comment]
Hi Armin

Very strange.

For the sake of a little less confusion, I will refer to the latest code as
V3.2A, and the earlier as V3.2

I repeated the earlier tests (using the ATtiny85 I have used for all tests
so far) and v3.2 works fine, but V3.2a reports that the device signature
cannot be read.
I tried another ATtiny85, with the same results.

Very odd.

Take care

Mike

**Comment by ArminJo** [comment]
Hi Mike,
there is no change in the code for reading signature, maybe you have different pin layout definitions activated?

**Comment by bWildered1** [comment]
Oops!

Hi Armin.

Sometimes I shouldn't be allowed out on my own.

Yes, you were correct; I had not modified the code to use the 'other'
interface.

To continue...
When a locked device is connected the program can do an automatic erase.
This might not be what a user might expect, or want.

    if (tDeviceType != DEVICE_UNKNOWN) {
        readFuses();
        bool tFusesAreLocked = readLockBits();

A boolean is set if the lock bits are set...

        if (tFusesAreLocked || tReceivedChar == 'e' || tReceivedChar ==
'E') {

Later, if that boolean is set an erase is performed, even if the 'e' ( or
'E') erase command had not been received.

After the switch is used to perform a fuse write to default values, the
program still seems to hang.
I don't know what is supposed to happen after the use of the switch, so
maybe this is the expected behaviour, and this does not affect my usage in
any way.


Serial Monitor Output
_______________________________________________________
START /home/mike/Arduino/AVR_HVSSTART
/home/mike/Arduino/AVR_HVSerialFuseProgrammerAndFlashErase3.21/AVR_HVSerialFuseProgrammerAndFlashErase3.21.ino
Version 3.2A from Jun 18 2019


Enter 'r' to only read fuses and lock bits...
Enter 'e' to erase flash and lock bits...
Enter 'w' or any other character or press button at pin 6 to to write fuses
to default...

Reading signature from connected ATtiny...
Signature is: 930B
Reading signature complete..

The ATtiny is detected as ATtiny85.

Reading fuse settings from ATtiny...
  LFuse: 22, HFuse: DF, EFuse: FF
Reading fuse values complete.

Reading lock bits...
  Lock: FC
    LB1 Programmed
    LB2 Programmed
Further programming of the Flash and EEPROM is disabled in High-voltage and
Serial Programming mode.
The Fuse bits are locked in both Serial and High-voltage Programming mode.
debugWire is disabled.
Additionally verification is also disabled in High-voltage and Serial
Programming mode.
Reading Lock Bits complete.


*Erasing flash and lock bits...Erasing complete.*

Reading / programming finished, allow a new run.


Enter 'r' to only read fuses and lock bits...
Enter 'e' to erase flash and lock bits...
Enter 'w' or any other character or press button at pin 6 to to write fuses
to default...
_________________________________________________________________________________________

Take care

Mike

**Pull request closed without merging**
